// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDS7d8LSB0ANIZdNFplAanBkdaBBdLCt1E',
    appId: '1:94060502223:web:4cae049c3e31eaff872bba',
    messagingSenderId: '94060502223',
    projectId: 'maturita-54231',
    authDomain: 'maturita-54231.firebaseapp.com',
    storageBucket: 'maturita-54231.appspot.com',
    measurementId: 'G-7XM9V5NJNQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6__5fjuhGisgt-VpAfs27b9qFu2pq_rc',
    appId: '1:94060502223:android:478672e764db026e872bba',
    messagingSenderId: '94060502223',
    projectId: 'maturita-54231',
    storageBucket: 'maturita-54231.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0wxYdi1PUf1_Gp-IaigqIgMeGIY9DOUY',
    appId: '1:94060502223:ios:6a80165ec14aa899872bba',
    messagingSenderId: '94060502223',
    projectId: 'maturita-54231',
    storageBucket: 'maturita-54231.appspot.com',
    iosBundleId: 'com.vaclav.tichy180.maturitaTichyRepo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0wxYdi1PUf1_Gp-IaigqIgMeGIY9DOUY',
    appId: '1:94060502223:ios:8b79e032debdf4c1872bba',
    messagingSenderId: '94060502223',
    projectId: 'maturita-54231',
    storageBucket: 'maturita-54231.appspot.com',
    iosBundleId: 'com.example.maturitaTichyRepo.RunnerTests',
  );
}
